import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { ThemeModeScript } from "flowbite-react";
import { Counter } from "./components/Counter";
import { Navigation } from "./components/Navigation";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "A Next app",
  description: "Generated by bay007",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="dark">
      <head>
        <ThemeModeScript />
      </head>

      <body className={inter.className + " mx-auto container"}>
        <Counter />
        <Navigation />
        {children}
      </body>
    </html>
  );
}
